source "%val{config}/plugins/plug.kak/rc/plug.kak"

plug "jdugan6240/powerline.kak" config %{
    powerline-start
}

plug "andreyorst/smarttab.kak"
set global tabstop 4
set global indentwidth 4

map global user y '<a-|>xclip -i -selection clipboard<ret>'

hook global InsertCompletionShow .* %{
    try %{
        # this command temporarily removes cursors preceded by whitespace;
        # if there are no cursors left, it raises an error, does not
        # continue to execute the mapping commands, and the error is eaten
        # by the `try` command so no warning appears.
        execute-keys -draft 'h<a-K>\h<ret>'
        map window insert <tab> <c-n>
        map window insert <s-tab> <c-p>
    }
}
hook global InsertCompletionHide .* %{
    unmap window insert <tab> <c-n>
    unmap window insert <s-tab> <c-p>
}

hook global InsertChar k %{ try %{
	exec -draft hH <a-k>jk<ret> d
	exec <esc>
}}

hook global NormalKey y|d|c %{ nop %sh{
	printf %s "$kak_main_reg_dquote" | xsel --input --clipboard
}}
